In [49]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [50]:
mp_key = "emUreNDiEdgEatR8YwlD3hfzF9Onx8tt"
mp_id = "mp-4636"

In [51]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Structure symmetry

In [52]:
i_atom = 7
i_symmop = 2

In [53]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [54]:
view.script('select scandium; color lightsalmon')
view.script('select copper; color white')
view.script('select oxygen; color pink')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [55]:
#d'abord, on cherche les vecteurs de base du réseau direct
direct_lattice = prim_struc.lattice.matrix 
print("Vecteurs de base du réseau direct (a, b, c) :")
print(direct_lattice)

#ensuite, les vecteurs de base du réseau réciproque
reciprocal_lattice = prim_struc.lattice.reciprocal_lattice.matrix
print("Vecteurs de base du réseau réciproque (a*, b*, c*) :")
print(reciprocal_lattice)


Vecteurs de base du réseau direct (a, b, c) :
[[ 3.10071979e+00 -2.47365000e-03  5.12053049e+00]
 [ 1.42765013e+00  2.75250708e+00  5.12053049e+00]
 [-4.07140000e-03 -2.47365000e-03  5.98617335e+00]]
Vecteurs de base du réseau réciproque (a*, b*, c*) :
[[ 2.02396889e+00 -1.05152981e+00  9.42049270e-04]
 [ 2.62826634e-04  2.28082359e+00  9.42677235e-04]
 [-1.73151354e+00 -1.05152923e+00  1.04800415e+00]]


In [56]:
spacegroup_analyzer = SpacegroupAnalyzer(prim_struc)

#on trouve le type de maille
lattice_type = spacegroup_analyzer.get_lattice_type()
print("Type de maille : ", lattice_type)

#le système cristallin
crystal_system = spacegroup_analyzer.get_crystal_system()
print("Système cristallin : ", crystal_system)


Type de maille :  rhombohedral
Système cristallin :  trigonal


In [57]:
#enfin, on trouve le groupe ponctuel
spacegroup_analyzer = SpacegroupAnalyzer(conv_struc)
point_group = spacegroup_analyzer.get_space_group_symbol()
print("Groupe ponctuel : ", point_group)

Groupe ponctuel :  R-3m
