<h1>Opérations de symétrie sur ScCuO2</h1>

<h2>Introduction</h2>

La molécule ScCuO2 présente plusieurs opérations de symétrie qui peuvent lui être appliquées. Dans ce notebook, nous allons explorer trois de ces opérations de symétrie : l'axe de rotation z, le plan de réflexion xy et le centre d'inversion placé à l'origine.

In [144]:
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display
from jupyter_jsmol.pymatgen import quick_view
from pymatgen.core.operations import SymmOp
import numpy as np

In [145]:
mp_key = "emUreNDiEdgEatR8YwlD3hfzF9Onx8tt"
mp_id = "mp-4636"

In [146]:
with MPRester(mp_key) as m:
    structure = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
analyze_struc = SpacegroupAnalyzer(conv_struc)

Sym = analyze_struc.get_symmetry_operations()  #en utilisant la commande print(Sym), j'ai sélectionné les éléments de symétrie que je voulais appliquer à mes atomes et gardé les matrices correspondantes
Sites = structure.sites

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [147]:
cif_filename = "structure.cif"
CifWriter(conv_struc).write_file(cif_filename)

jsmol_view_original = JsmolView.from_file(cif_filename)
display(jsmol_view_original)
jsmol_view_original.script('select scandium; color lightsalmon')
jsmol_view_original.script('select copper; color palegreen')
jsmol_view_original.script('select oxygen; color lightblue')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [148]:

sites = conv_struc.sites
    
sc_coord = sites[0].frac_coords
cu_coord = sites[4].frac_coords
ox_coord = sites[9].frac_coords

#je choisis un atome Sc, un atome Cu et un atome O

op_sym = SpacegroupAnalyzer(conv_struc).get_point_group_operations()

# Opérations de symétrie

<h2>Inversion au centre sur Sc</h2>

Nous allons étudier l'opération d'inversion centrée en l'origine sur l'atome de Sc. L'opération d'inversion peut être définie comme ceci : 
$\left [\begin{matrix}-1 & 0 & 0\\0 & -1 & 0\\0 & 0 & -1\end{matrix}\right]$ 
$ \left [\begin{matrix}x\\y \\z\end{matrix}\right]$ 
= $ \left [\begin{matrix}-x\\-y \\-z\end{matrix}\right]$.

On peut remarquer par la suite que la matrice tau est nulle, ce qui signifie qu'il n'y a pas de translation.

Le déterminant de la matrice vaut -1. Il s'agit d'une opération de deuxième espèce, qui inverse la chiralité. 



In [149]:
index_op_sym = 2
op_1 = op_sym[index_op_sym-1]

print("Matrice de transformation et vecteur tau")
print(op_1)

print("Position initiale de l'atome Sc")
print(sc_coord)

print("Position de l'atome Sc après avoir appliqué l'opération d'inversion")
inverted_sc = op_1.operate(sc_coord)
print(inverted_sc)

Matrice de transformation et vecteur tau
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Position initiale de l'atome Sc
[0.33333333 0.66666667 0.16666667]
Position de l'atome Sc après avoir appliqué l'opération d'inversion
[-0.33333333 -0.66666667 -0.16666667]


In [151]:
jsmol_view_inversion = JsmolView.from_file(cif_filename)
display(jsmol_view_inversion)
jsmol_view_inversion.script('select scandium; color lightsalmon')
jsmol_view_inversion.script('select copper; color palegreen')
jsmol_view_inversion.script('select oxygen; color lightblue')
jsmol_view_inversion.script(f'draw SYMOP {index_op_sym} {{atomno = {1}}}') 


JsmolView(layout=Layout(align_self='stretch', height='400px'))

<h2>Roto-réflexion sur Cu</h2>

Nous allons étudier l'opération de roto-réflection. On a d'abord une rotation dans le plan (x, y). On transforme x en x-y et y en x. Ensuite, on a une réflexion par rapport au plan xy. On transforme donc z en -z. L'équation associée à cette opération est la suivante : 
$\left [\begin{matrix}1 & -1 & 0\\1 & 0 & 0\\0 & 0 & -1\end{matrix}\right]$ 
$ \left [\begin{matrix}x\\y \\z\end{matrix}\right]$ 
= $ \left [\begin{matrix}x-y\\x \\-z\end{matrix}\right]$.

On peut remarquer par la suite que la matrice tau est nulle, ce qui signifie qu'il n'y a pas de translation.

Le déterminant de la matrice vaut -1. Il s'agit d'une opération de deuxième espèce, qui inverse la chiralité.

In [152]:
index_op_sym2 = 6
op_2 = op_sym[index_op_sym2-1]

print("Matrice de transformation et vecteur tau")
print(op_2)

print("Position initiale de l'atome Cu")
print(cu_coord)

print("Position de l'atome Cu après avoir appliqué l'opération de roto-réflexion")
rotated_cu = op_2.operate(cu_coord)
print(rotated_cu)

Matrice de transformation et vecteur tau
Rot:
[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Position initiale de l'atome Cu
[0.66666667 0.33333333 0.33333333]
Position de l'atome Cu après avoir appliqué l'opération de roto-réflexion
[ 0.33333333  0.66666667 -0.33333333]


In [154]:
jsmol_view_rotoreflection = JsmolView.from_file(cif_filename)
display(jsmol_view_rotoreflection)
jsmol_view_rotoreflection.script('select scandium; color lightsalmon')
jsmol_view_rotoreflection.script('select copper; color palegreen')
jsmol_view_rotoreflection.script('select oxygen; color lightblue')
jsmol_view_rotoreflection.script(f'draw SYMOP {index_op_sym2} {{atomno = {2}}}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

<h2>Réflexion orthogonale par rapport au plan P: x+y = 0 sur l'atome O</h2>

Nous allons étudier l'opération de réflexion sur l'atome O. Il s'agit d'une réflexion dite orthogonale par rapport au plan P : x + y = 0. Cette rotation peut être définie comme : 
$\left [\begin{matrix}0 & -1 & 0\\-1 & 0 & 0\\0 & 0 & 1\end{matrix}\right]$ 
$ \left [\begin{matrix}x\\y \\z\end{matrix}\right]$ 
= $ \left [\begin{matrix}-y\\-x \\z\end{matrix}\right]$.

On peut remarquer par la suite que la matrice tau est nulle, ce qui signifie qu'il n'y a pas de translation.

Le déterminant de la matrice vaut -1. Il s'agit d'une opération de deuxième espèce espèce, qui inverse la chiralité.

In [155]:
index_op_sym3 = 8
op_3 = op_sym[index_op_sym3-1]

print("Matrice de transformation et vecteur tau")
print(op_3)

print("Position initiale de l'atome O")
print(ox_coord)

print("Position de l'atome O après avoir appliqué l'opération de rotation")
rotated_o = op_3.operate(ox_coord)
print(rotated_o)

Matrice de transformation et vecteur tau
Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Position initiale de l'atome O
[0.66666667 0.33333333 0.44016333]
Position de l'atome O après avoir appliqué l'opération de rotation
[-0.33333333 -0.66666667  0.44016333]


In [156]:
jsmol_view_rotation = JsmolView.from_file(cif_filename)
display(jsmol_view_rotation)
jsmol_view_rotation.script('select scandium; color lightsalmon')
jsmol_view_rotation.script('select copper; color palegreen')
jsmol_view_rotation.script('select oxygen; color lightblue')
jsmol_view_rotation.script(f'draw SYMOP {index_op_sym3} {{atomno = {3}}}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))